package my.edu.ukm.ftsm.ecommerce.demo;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import my.edu.ukm.ftsm.ecommerce.search.CatalogCategory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Jackson mapping of {@code demo/catalog.json} (generated by scripts/p5a/gen_catalog.py) and its validation, which runs
 * before any database work (docs/phases/P5a.md §6.2).
 */
public record CatalogJson(int version, String generator, List<ProductEntry> products, List<ItemEntry> items) {

    public static final String RESOURCE = "demo/catalog.json";

    private static final Set<String> LANGS = Set.of("en", "ms", "zh");
    private static final Set<String> CONDITIONS = Set.of("NEW", "LIKE_NEW", "USED");
    private static final Pattern SELLER = Pattern.compile("^seller(0[1-9]|1[0-9]|20)$");
    private static final BigDecimal MAX_PRICE = new BigDecimal("100000");

    public record ProductEntry(long id, String lang, String name, String description, String category,
                               BigDecimal price, int totalStock, String imageUrl) {}

    public record ItemEntry(long id, String lang, String title, String description, String category, String condition,
                            BigDecimal price, String sellerKey, String imageUrl) {}

    public static CatalogJson load() {
        return read(new ClassPathResource(RESOURCE));
    }

    public static CatalogJson read(Resource resource) {
        ObjectMapper mapper = new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)
                .configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true);
        try (InputStream in = resource.getInputStream()) {
            return mapper.readValue(in, CatalogJson.class);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot read demo catalogue " + resource.getDescription(), e);
        }
    }

    /** @throws IllegalArgumentException listing every problem with the id it belongs to */
    public CatalogJson validate() {
        List<String> problems = new ArrayList<>();
        Set<Long> ids = new HashSet<>();
        for (ProductEntry p : nullSafe(products)) {
            String ref = "product " + p.id();
            if (!ids.add(p.id())) {
                problems.add(ref + ": duplicate id");
            }
            if (p.id() < 1001 || p.id() > 4999) {
                problems.add(ref + ": id must be 1001-4999");
            }
            text(problems, ref, "name", p.name(), 200, true);
            text(problems, ref, "description", p.description(), 2000, false);
            common(problems, ref, p.category(), p.price(), p.lang());
            if (p.totalStock() < 0) {
                problems.add(ref + ": totalStock must be >= 0");
            }
        }
        for (ItemEntry i : nullSafe(items)) {
            String ref = "item " + i.id();
            if (!ids.add(i.id())) {
                problems.add(ref + ": duplicate id");
            }
            if (i.id() < 5001 || i.id() > 9999) {
                problems.add(ref + ": id must be 5001-9999");
            }
            text(problems, ref, "title", i.title(), 200, true);
            text(problems, ref, "description", i.description(), 2000, false);
            common(problems, ref, i.category(), i.price(), i.lang());
            if (!CONDITIONS.contains(i.condition())) {
                problems.add(ref + ": condition '" + i.condition() + "' is not NEW, LIKE_NEW or USED");
            }
            if (i.sellerKey() == null || !SELLER.matcher(i.sellerKey()).matches()) {
                problems.add(ref + ": unknown sellerKey '" + i.sellerKey() + "'");
            }
        }
        if (!problems.isEmpty()) {
            throw new IllegalArgumentException("invalid demo catalogue (" + problems.size() + " problems): "
                    + String.join("; ", problems));
        }
        return this;
    }

    private static void common(List<String> problems, String ref, String category, BigDecimal price, String lang) {
        if (CatalogCategory.parse(category).isEmpty()) {
            problems.add(ref + ": unknown category '" + category + "'");
        }
        if (price == null || price.signum() <= 0 || price.compareTo(MAX_PRICE) > 0
                || price.stripTrailingZeros().scale() > 2) {
            problems.add(ref + ": price must be > 0 and <= 100000 with at most 2 decimals");
        }
        if (!LANGS.contains(lang)) {
            problems.add(ref + ": lang '" + lang + "' is not en, ms or zh");
        }
    }

    private static void text(List<String> problems, String ref, String field, String value, int max, boolean required) {
        int len = value == null ? 0 : value.length();
        if ((required && len == 0) || len > max) {
            problems.add(ref + ": " + field + " must be " + (required ? "1" : "0") + "-" + max + " characters");
        }
    }

    private static <T> List<T> nullSafe(List<T> list) {
        return list == null ? List.of() : list;
    }
}
